### ISSUE TITLE
setupNetworkWicked fails on wicked 0.6.11 (SLES12SP0)

### ISSUE THREAD

**Issue by ipeoshir** [openSUSE/kiwi#626] opened 2017-01-24 10:29 UTC
Images created with kiwi 7.03.108-60.1 - 7.04.22  cannot boot from network if it was built with an old wicked version such as one found on SLES12SP0. The following error is found on boot.kiwi log file:

> $ wicked test dhcp4 --request - -- eth0
> + echo '<request' 'type="lease"><lease-time>3600</lease-time></request>'
> Unsupported command test
> 

The same command works fine on wicked 0.6.38 (SLES12SP2) as we can read in the same log file:

> $ wicked test dhcp4 --request - -- eth0
> + echo '<request' 'type="lease"><lease-time>3600</lease-time></request>'
> + '[' 0 = 0 ']'
> + export PXE_IFACE=eth0
> + PXE_IFACE=eth0
> 

This was working fine with older versions of kiwi (7.02.77-1.1). To setup the network, I had to repack initrd with an older "KIWILinuxRC.sh" code, import it (". /KIWILinuxRC.sh") and run "setupNetwork" in maintanance mode.

**Comment by davidcassany** [comment] 2017-01-24 11:34
@ipeoshir thanks for reporting that,  I´ll have a look at what changed regarding that wicked tool usage.

**Comment by davidcassany** [comment] 2017-01-26 11:24
@ipeoshir I have done little research and I noticed the issue is solved by installing the official wicked update for SLE12-SP0. Using the update repository of SLE12-SP0 wicked gets updated (v0.6.31) and the issue is solved.

In Wicked v0.6.11 test command was not still implemented, which is used by the kiwi boot code; so the solution is to move from SLE12SP0 to upper versions or enable SLE12SP0 updates.

We are not considering to make a patch for that as we expect to keep using wicked in the future and there are already updates solving it. I am closing the issue.

**Closed by davidcassany** 2017-01-26 11:24 UTC
