### ISSUE TITLE
Kiwi & systemd fork-bomb system while executing config.sh

### ISSUE THREAD

**Issue by v-fox** [openSUSE/kiwi#525] opened 2015-11-28 13:45 UTC
After I updated to "The Tumbleweed Product" and after the issue of inaccessible dependencies [has been dealt with](http://lists.opensuse.org/opensuse-packaging/2015-11/msg00054.html) the worse one arisen: my system seems to be fork-bombed by systemd processes launched in kiwi chroot while executing [this config.sh](https://github.com/v-fox/live_opensuse_hsf/blob/75871b92c103affc8d211eb841a2c1763347d4ae/source/config.sh) which worked fine previously. Here's small snippet from dmesg when it oom-killed everything:
```
Nov 26 23:55:13 arsenal.patriots kernel: [17083]     0 17083     3835      264      12       3        0             0 config.sh
Nov 26 23:55:13 arsenal.patriots kernel: [17146]     0 17146     6315       53      16       3        0             0 systemctl
Nov 26 23:55:13 arsenal.patriots kernel: [17147]     0 17147     2940       51      11       3        0             0 systemd-sysv-in
Nov 26 23:55:13 arsenal.patriots kernel: [17149]     0 17149     7281     1367      18       3        0             0 chkconfig
```
The last 3 lines repeat gazillion times.

If I manually chroot right after that and run commands by hand - everything works fine.

**Comment by v-fox** [comment] 2015-11-30 12:14
Hmmm... I've changed all `systemctl {disable/enable}` to `base{Remove/Insert}Service` and it didn't fail even though there should be no difference.

**Comment by schaefi** [comment] 2015-11-30 14:03
sorry I have no idea what is causing this. actually config.sh ist just called by kiwi and completely under user control. whatever systemd does here it seems not a problem of kiwi to me. I'm also not able to reproduce this

kiwi will fail if config.sh returns with an exit code different from zero

**Comment by v-fox** [comment] 2015-11-30 14:12
By "fail" here I mean "ate up all 8 GB of my RAM and was killed by kernel" :] I'm sure it's a systemd bug but what weird is that it does not happen in non-kiwi chroot or with base{Remove/Insert}Service.

**Comment by schaefi** [comment] 2015-11-30 14:26
yes weird, do you see the same issue on openSUSE 13.2, or Leap42.1 ?

**Comment by schaefi** [comment] 2015-11-30 14:27
I must admit I'm not using tumbleweed

**Comment by v-fox** [comment] 2015-11-30 14:42
I'm on Tumbleweed now, haven't had Leap, on 13.2 there were no such issue, I used that config.sh fine. This is why I think that this is some kind of systemd regression but what's interesting here is what in kiwi could trigger it.

**Comment by schaefi** [comment] 2015-12-23 10:00
I don't think this one can be fixed in the scope of kiwi

**Closed by schaefi** 2015-12-23 10:00 UTC
