### ISSUE TITLE
yum and zypper complain about missing lock files

### ISSUE THREAD

**Issue by mmohring** [openSUSE/kiwi#487] opened 2015-09-08 15:06 UTC
with the current KIWI version v7.03.17, yum and zypper complain now about a missing lock file. This happens when using KIWI inside OBS, which means the host OS for building == target OS, this is how OBS calls KIWI.

CentOS 6.x, RHEL 6.x and SUSE SLE 11 SP3 run into an error (other distros might also be affected). The newer distros CentOS 7.x, RHEL 7.x, SLE 12, openSUSE 13.x etc. are working.

- RHEL 6.x, CentOS 6.x

[ 1345s] + /usr/bin/yum -c /var/cache/kiwi/yum/yum.conf -y --installroot=/usr/src/packages/KIWIROOT-vmx install basesystem filesystem yum
[ 1346s] Could not open lock /usr/src/packages/KIWIROOT-vmx/var/run/yum.pid: [Errno 2] No such file or directory: '/usr/src/packages/KIWIROOT-vmx/var/run/yum.pid'
[ 1346s] Can't create lock file; exiting

- SUSE SLE 11 SP3 (potentially all SLE 11 I guess):

[ 712s] + /usr/bin/zypper --non-interactive --pkg-cache-dir /var/cache/kiwi/packages --reposd-dir /usr/src/packages/KIWIROOT-vmx//var/cache/kiwi/zypper/repos --solv-cache-dir /usr/src/packages/KIWIROOT-vmx//var/cache/kiwi/zypper/solv --cache-dir /usr/src/packages/KIWIROOT-vmx//var/cache/kiwi/zypper --config /var/cache/kiwi/zypper/zypper.conf.3848 --no-gpg-checks --root /usr/src/packages/KIWIROOT-vmx install --auto-agree-with-licenses --no-recommends filesystem glibc-locale bootsplash-branding-SLES gfxboot gfxboot-branding-SLES vmware-guest-kmp-default xen-kmp-default zypper
[ 712s] Cant open /usr/src/packages/KIWIROOT-vmx/var/run/zypp.pid

**Comment by mmohring** [comment] 2015-09-08 15:14
I will downgrade to v7.03.15 (the version before the /var/run changes) and report back if error still happens.

**Comment by schaefi** [comment] 2015-09-08 15:33
Sorry I'm not able to reproduce this.  I have set up a fresh sles11 sp3 build system and called kiwi on it. no problems. This seems to be an inconsistency when the buildservice builds it ? I have no way to influence how the buildservice setup its build environment though

**Comment by mmohring** [comment] 2015-09-08 15:57
v7.03.15 works. So its some change between v7.03.15 and v7.03.17. I use OBS with virtualized workers on KVM. I will try myself in addition to track this change down causing this.

**Comment by mmohring** [comment] 2015-09-09 11:01
Moved now to KIWI version v7.03.17 inside OBS minus commit a887b4a1243c44abf182321e604197d0feb6039b. Will try to figure out which of the lines of this commit causes the problem.

**Comment by mmohring** [comment] 2015-09-09 11:23
What can be different to running KIWI without OBS? The build script version deployed in the OBS or using a Virtual Machine for building. Does running KIWI standalone use the build script ?

**Comment by schaefi** [comment] 2015-09-09 13:05
there are many of differences. The buildservice sets up an own system around the kiwi call. You can see that if you look on the first lines of an "osc buildlog", they treat udev rules in a special way and also other parts are different, even the kernel might be a special one

**Comment by mmohring** [comment] 2015-09-14 13:42
I found the problem, will make a fix, test it and submit it

**Comment by schaefi** [comment] 2015-09-14 14:00
>    I found the problem, will make a fix, test it and submit it

Sounds great, I'm excited to see what caused it. Thanks

**Comment by mmohring** [comment] 2015-09-23 10:40
The issue is that there are two variants of /var/run: before systemd there was only /var/run. With the introduction of systemd there are now /run and /var/run, which are mounted to a tmpfs, same location. As far as I know there is no variant with a symlink. I checked this with SLE 11/12, openSUSE 13.x, CentOS 6.x / 7.x, RHEL 6.x / 7.x. I think this must also be reflected in the firstboot initrd generated by KIWI. At the moment if I see it correctly the firstboot initrd creates the variant with /run and /var/run using a tmpfs. This is not correct for old distros before systemd was introduced. For example a CentOS 6.x VMX image has failures at the first boot. When a new initrd is then created at the first boot, this does not have the /run /var/run mounted to a tmpfs. So the second boot is then "normal" and working correctly, and any subsequent regenerations of initrd, for example by config or kernel updates.

**Comment by mmohring** [comment] 2015-09-23 10:42
I think I open a new issue for the initrd mount problem for /run and /var/run.

**Comment by mmohring** [comment] 2015-09-23 10:47
The resolutions when using KIWI inside OBS is that because host OS == image OS, I check for the systemd vs. non systemd case with /run /var/run on a tmpfs and reflect it in the image root fs. The symlink variant is removed, it does not exist on any distro I know of that is supported by KIWI.

**Comment by mmohring** [comment] 2015-10-01 10:23
I have created a pull request #500 for the separate initrd issue.

**Comment by schaefi** [comment] 2015-11-03 15:57
This one is fixed in commit#9b477659e728268fd40cfce2ad281d0f408e990d

**Closed by schaefi** 2015-11-03 15:57 UTC
